name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Ganti 'main' jika nama branch Anda berbeda

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Diperbarui ke v4 (Node 24 ready)

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href /pam-p7-2026-ifs23003/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Diperbarui ke v4 (Node 24 ready)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
